---
title: "Briggslabjournaclub_01182021"
author: "sbsambado"
date: "1/18/2021"
output: html_document
---
This is plain script. 

I am creating a Rmarkdown script for journal club.



```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r load libraries}
library(tidyverse)
library(readr)
library(ggplot2)

clean_background <- theme(plot.background = element_rect("white"),
        panel.background = element_rect("white"),
        panel.grid = element_line("white"),
        axis.line = element_line("gray25"),
        axis.text = element_text(size = 12, color = "gray25"),
        axis.title = element_text(color = "gray25"),
        legend.text = element_text(size = 12),
        legend.key = element_rect("white"))

```


```{r upload data and explore}


np_parks <- read_csv("National Parks Visitation Data.csv")
class(np_parks)

# explore

names(np_parks)
dim(np_parks)
class(np_parks)

summary(np_parks$Visitors)
```


```{r}

df1 <- select(np_parks, Region:YearRaw)

df2<- filter(df1, Region == "SE" & Type == "National Park")

df3 <- arrange(df2, Code, YearRaw)

df4 <- mutate(df3, kVis = Visitors/1000)

summary(df4)

class(df5$YearRaw)

unique(df5$YearRaw)

# == equal
# != not equal

df5 <- filter(df4, YearRaw != "Total")

df5$YearRaw <- as.numeric(df5$YearRaw)


# compare

dim(np_parks)
dim(df5)
```


